# Describes the format for available services for KEBA charging staitons

start:
  name: Authorize charging process
  description: >
    Authorizes a charging process with the given RFID tag.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba
    rfid:
      name: RFID tag
      description: RFID tag to be used (need to be configured within the charging station first)
      selector:
        text:
    rfid_class:
      name: RFID class (optional)
      description: RFID class to be used (RFID color code)
      selector:
        text:

stop:
  name: Deauthorize charging process
  description: >
    Deauthorizes the running charging process with the given RFID tag.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba
    rfid:
      name: RFID tag
      description: RFID tag to be used (need to be configured within the charging station first)
      selector:
        text:

set_energy:
  name: Set energy
  description: Sets the energy target after which the charging process stops.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba
    energy:
      name: Energy
      description: The energy target to stop charging. Setting 0 disables the limit.
      selector:
        number:
          min: 0
          max: 100
          step: 0.1
          unit_of_measurement: kWh

set_current:
  name: Set current
  description: Sets the maximum current for charging processes.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba
    current:
      name: Current
      description: >
        The maximum current used for the charging process.
        The value is limited by the DIP-switch settings and the used cable of the
        charging station.
      required: true
      default: 6
      selector:
        number:
          min: 6
          max: 63
          step: 0.001
          unit_of_measurement: A
    delay:
      name: Delay
      description: The delay in seconds after which the defined current should be set.
      default: 0
      selector:
        number:
          min: 0
          max: 860400
          step: 1
          unit_of_measurement: seconds

set_failsafe:
  name: Set failsafe
  description: >
    Set the failsafe mode of the charging station. If all parameters are 0, the failsafe mode will be disabled.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba
    mode:
      name: Failsafe mode
      description: >
        Failsafe on or off
      default: true
      selector:
        boolean:
    timeout:
      name: Failsafe timeout
      description: >
        Timeout after which the failsafe mode is triggered, if set_current was not executed during this time.
      default: 30
      selector:
        number:
          min: 1
          max: 600
          step: 1
          unit_of_measurement: seconds
    fallback_value:
      name: Failsafe fallback
      description: >
        Fallback current to be set after timeout.
      default: 6
      selector:
        number:
          min: 6
          max: 63
          step: 0.001
          unit_of_measurement: A
    persist:
      name: Failsafe persist
      description: If failsafe_persist is False, the failsafe option is only used until charging station reboot. If failsafe_persist is True, the failsafe option will survive a reboot.
      default: false
      selector:
        boolean:

set_charging_power:
  name: Set charging power
  description: Set the charging power in kW if a charging operation is running. This service internally identifies the number of phases used for charging and sets the charging charging current to match the charging power as good as possible.
  fields:
    device_id:
      name: Wallbox
      description: The Keba Wallbox
      required: true
      selector:
        device:
          integration: keba
    power:
      name: Charging power
      description: Target charging power in kW
      required: true
      default: 11
      selector:
        number:
          min: 0
          max: 22
          step: 0.1
          unit_of_measurement: kW
    round_up:
      name: Round up charging power
      description: The charging station only supports to set current on all three phases. When round_up is enabled, the charging current will round up so that at least the given charging power is reached. Otherwise it is rounded down, so that less than the given charging power is reached.
      required: true
      default: false
      selector:
        boolean:
    stop_below_6_A:
      name: Stopping charging if given power value is too small
      description: If enabled, the charging process will stop if given charging power is too small. Otherwise, charging will continue with 6 A per phase.
      required: true
      default: true
      selector:
        boolean:
